@startgantt

title VendorGuard Project - Gantt Chart

printscale weekly
project starts 2025-07-07

-- Modules --
[Database Schema & ORM Setup] lasts 2 weeks
[Authentication & Role Management] lasts 2 weeks
[Authentication & Role Management] starts at [Database Schema & ORM Setup]'s end
[Vendor Management & KYC Module] lasts 2 weeks
[Vendor Management & KYC Module] starts at [Authentication & Role Management]'s end
[Orders & Invoice Module] lasts 2 weeks
[Orders & Invoice Module] starts at [Vendor Management & KYC Module]'s end
[Disputes & Returns Module] lasts 1 weeks
[Disputes & Returns Module] starts at [Orders & Invoice Module]'s end
[AI Risk Scoring Engine] lasts 2 weeks
[AI Risk Scoring Engine] starts at [Disputes & Returns Module]'s end
[Performance & Anomaly Detection] lasts 2 weeks
[Performance & Anomaly Detection] starts at [AI Risk Scoring Engine]'s end
[Dashboard & Analytics UI] lasts 2 weeks
[Dashboard & Analytics UI] starts at [Performance & Anomaly Detection]'s end
[Testing & Deployment] lasts 1 weeks
[Testing & Deployment] starts at [Dashboard & Analytics UI]'s end

@endgantt
